import type { Metadata } from "next";
import { helvetica } from "./fonts";
import "./globals.css";

import { TextLogo, Menus } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helvetica.className} font-normal bg-white`}>
        <div className="w-full fixed top-0 flex items-center gap-1 h-14 bg-white z-10">
          <TextLogo className="mt-[-2px] ml-13 cursor-pointer">
            moonlight
          </TextLogo>
        </div>
        <Menus />
        <div className="pt-14">{children}</div>
      </body>
    </html>
  );
}
